### ISSUE TITLE
Number of dice to roll is not selectable.

### ISSUE THREAD

**Issue by Sorellia** [puddinbustra/swnpretty#2]
See below:
![Capture](https://user-images.githubusercontent.com/89615315/132064398-4ce95880-528d-4bfe-8120-64abf62e9ee8.PNG)

First of all, I will preface that this picture was taken on a custom version of your sheet that I've been tinkering with (I've been working on my next set of additions before I ponder whether or not to tackle starships and vehicles), but I have also tested this on a version pulled right from your GitHub repo and this issue applies there too.

The menu for bonuses doesn't show the dice selection options here, and it's to do with your template file for this bonuses section; if I were to guess, it's struggling to obtain the skills from the sheet, but I'm not quite sure in this case.

Figured you would want to know.

**Comment by puddinbustra** [comment]
Yeah, I know. I'm working on that. I've almost finished the dice stuff, and
will add global encumbrance next.

**Comment by puddinbustra** [comment]
Should be all fixed now
